networks:
 docker:
    name: docker

services:
  cryptography:
    image: ghcr.io/sandialabs/sync-services/cryptography:1.0.0
    container_name: cryptography
    networks:
      - docker

  journal:
    image: ghcr.io/sandialabs/sync-services/ledger:1.0.0
    container_name: journal
    networks:
      - docker
    depends_on:
      - cryptography
    environment:
      SECRET: ${SECRET}
      PERIODICITY: ${PERIODICITY:-2}
      CRYPTOGRAPHY: http://cryptography.docker

  explorer:
    image: ghcr.io/sandialabs/sync-services/explorer:1.0.0
    container_name: explorer
    networks:
      - docker
    depends_on:
      - journal
    command: python service.py --secret $SECRET --journal http://journal.docker/interface --port 80

  interface:
    image: nginx:stable-alpine
    container_name: interface
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - journal
    networks:
      - docker
    ports:
      - "${PORT:-8192}:80"
