networks:
 docker:
    name: docker

services:
  cryptography:
    image: synchronic-web/cryptography-service:latest
    networks:
      - docker

  journal:
    image: synchronic-web/journal-sdk:latest
    volumes:
      - ./source.scm:/srv/source.scm
      - ./run.sh:/srv/run.sh
    networks:
      - docker
    depends_on:
      - cryptography
    environment:
      SEED: ${SEED}
      PERIODICITY: ${PERIODICITY:-0}
      CRYPTOGRAPHY: "http://cryptography.docker"
      REST: ${PROMISE_INTERVAL:-2048} ${PROOF_INTERVAL:-2048}
    command: ./run.sh

  interface:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./tls_certificate.pem:/etc/ssl/certs/tls_certificate.pem
      - ./tls_private.pem:/etc/ssl/private/tls_private.pem
    depends_on:
      - journal
    networks:
      - docker
    ports:
      - "${PORT:-8192}:80"
      - "443:443"
