networks:
 docker:
    name: docker

services:
  cryptography:
    image: ghcr.io/sandialabs/sync-services/cryptography:1.0.0
    networks:
      - docker

  journal:
    image: ghcr.io/sandialabs/sync-journal/journal-sdk:1.0.1
    volumes:
    networks:
      - docker
    depends_on:
      - cryptography
    environment:
      SEED: ${SEED}
      PERIODICITY: ${PERIODICITY:-2}
      CRYPTOGRAPHY: http://cryptography.docker
    command: ./run.sh

  explorer:
    image: ghcr.io/sandialabs/sync-services/explorer:1.0.0
    networks:
      - docker
    depends_on:
      - journal
    command: python service.py --secret $SECRET --journal http://journal.docker

  interface:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - journal
    networks:
      - docker
    ports:
      - "${PORT:-8192}:80"
