name: Cryptography Service

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install rust
        uses: moonrepo/setup-rust@v1
      - name: Login to Github registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and push versioned Docker image
        run: |
          cd ./services/cryptography
          version=$( cargo pkgid | cut -d '@' -f 2 )
          docker build ./services/cryptography --tag ghcr.io/${{ github.repository }}/cryptography:$version
          docker push ghcr.io/${{ github.repository }}/cryptography:$version
      - name: Retag and push latest Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag ghcr.io/${{ github.repository }}/cryptography:$( cargo pkgid | cut -d '@' -f 2 ) \
                     ghcr.io/${{ github.repository }}/cryptography:latest 
          docker push ghcr.io/${{ github.repository }}/cryptography:latest
